### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [mp3guy/ElasticFusion#1]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [Frame](https://github.com/mp3guy/ElasticFusion/blob/544da79fad6426fa6218dc5cef61acf4ac2e1822/Core/src/Ferns.h#L114 "Destructor for Frame")
* [GPUTexture](https://github.com/mp3guy/ElasticFusion/blob/544da79fad6426fa6218dc5cef61acf4ac2e1822/Core/src/GPUTexture.cpp#L53 "Destructor for GPUTexture")
* [MainController](https://github.com/mp3guy/ElasticFusion/blob/544da79fad6426fa6218dc5cef61acf4ac2e1822/GUI/src/MainController.cpp#L120 "Destructor for MainController")

**Comment by mp3guy** [comment]
I think this is just a habit from when I used malloc and free...
