### ISSUE TITLE
ROS integration

### ISSUE THREAD

**Issue by mjedmonds** [mp3guy/ElasticFusion#10]
I was wondering if there had been any more consideration for ROS integration. The tight coupling with the GPU doesn't have to translate from ROS's perspective (e.g. send messages to ROS at a slower interval than the internal communication between mapping/tracking).

I'd be willing to pursue trying to get a ROS wrapper up and running, but was wondering if the creators could elaborate on why they believe ROS integration isn't possible. 

Integrating ROS would greatly expand the use and exposure of this platform. I've been evaluating SLAM systems for a couple of months, and I haven't come across one as robust as this one.

**Comment by mp3guy** [comment]
I'm sure it's possible, you're just going to introduce a lot of lag (comparably), and need to decide what the map representation inside ROS will be.
