### ISSUE TITLE
ElasticFusion and CUDA 6.5 

### ISSUE THREAD

**Issue by alessmosca** [mp3guy/ElasticFusion#100]
Hello , 
for my research I'm trying to use elasticFusion on a Jetson TK1 ( a 32bit CPU board with CUDA ). since is a 32bit ARM CPU i could not install the minimum version required, the 7.0, so I'm wondering if there is a way to use Efusion on that board. 
I manage to compile everything but seems is crushing in some specific command line like: 
```
    resizeStream = new Resize(Resolution::getInstance().width() ,
                              Resolution::getInstance().height() ,
                              Resolution::getInstance().width()  / 2,
                              Resolution::getInstance().height()  / 2);
```

is there someone who could help me ?

**Comment by zssjh** [comment]
@alessmosca I'm trying to use elasticFusion on a Jetson TK1 too and I met a segmentfault when ./Elasticfusion， what is the reason and what should I do ?Many many thanks!
