### ISSUE TITLE
Running ElasticFusion with .freiburg file

### ISSUE THREAD

**Issue by Mirnail** [mp3guy/ElasticFusion#105]
I run the EF on **rgbd_dataset_freiburg1_desk** . I retrieved the ".freiburg"  trajectory file. I a bit  changed it to the format that EF expects to run it with "-p" flag. I expected to get same construction because i am running the exact same trajectory output from previous run. But it seems that i missing something. I am getting totally distorted graph.

I just changed timestamp from seconds to microsenconds by multiplying it to 1000000. 

`/path_to_EF/./ElasticFusion -l /path_to_data/rgbd_dataset_freiburg1_desk/test2.klg -p /path_to_data/rgbd_dataset_freiburg1_desk/modified_freiburg.txt`

Can you tell me what i am missing? Where could be my mistake?

**Comment by Mirnail** [comment]
Solved by finding transformation matrix .

**Comment by AkshayHinduja** [comment]
Hi @Mirmix could you tell me what changes you made the pose file? I am trying to do the same.

**Comment by Mirmix** [comment]
| 0 0 1|
|-1 0 0|
|0 -1 0|

You should apply transformation matrix to both rotation and translation

**Comment by AkshayHinduja** [comment]
@Mirmix weirdly though I always fall into the assert n==8 break point and even if I comment that out (in Groundtruthodometry.cpp) the camera pose remains static, with surfels being drawn on the same patch continuosly. Did you make changes only in groundtruthodometry.cpp?

**Comment by Mirmix** [comment]
Is your input file in this format 

`          "%llu,%f,%f,%f,%f,%f,%f,%f"`

It should be in above format probably it is a reason of assert failure.

**Comment by AkshayHinduja** [comment]
Yes, I ensured that I am saving in the same format as its reading in by typecasting in the llu/f formats accordingly. Still it falls into the assertion. It shows n = 1, which I believe means it doe snot read beyond the timestamp perhaps?

**Comment by Mirmix** [comment]
Can you copy and paste your file here. At least first few lines. And is your timestamp information same with inside the klg file.

**Comment by AkshayHinduja** [comment]
I figured out the error I was making in reading the lines, and that is working fine now. For the transformation matrix, are you applying this transformation to the vector t and quaternion q (after converting to a rotation matrix) in  GroundTruthOdometry::loadTrajectory() and then pushing it to the isometry T?  
My reconstruction is still a bit messy on doing that though.

**Comment by Mirmix** [comment]
You can apply tramsformation matrix directly on quaternion. 
```
| 0 0 1 0|   |    Rx    |
|-1 0 0 0|   |    Ry    |
|0 -1 0 0| * |   Rz     |
|0  0 0 1|    |   Rw    |
```

**Comment by AkshayHinduja** [comment]
Got it, thank you!

**Comment by Mirmix** [comment]
It was my pleasure.

**Comment by Mirmix** [comment]
It was my pleasure :)

**Comment by Viky397** [comment]
Hello, I am trying to pass in my own groundtruth pose file and am running into the n==8 assertion error. Could you please let me know what you did to fix this error? :) @AkshayHinduja

**Comment by tfy14esa** [comment]
> I figured out the error I was making in reading the lines, and that is working fine now. For the transformation matrix, are you applying this transformation to the vector t and quaternion q (after converting to a rotation matrix) in GroundTruthOdometry::loadTrajectory() and then pushing it to the isometry T? My reconstruction is still a bit messy on doing that though.

I think I am facing the same issue as you had. What changes did you make when reading the file? Did you alter the source code?
