### ISSUE TITLE
Segfault when using core API

### ISSUE THREAD

**Issue by 5yler** [mp3guy/ElasticFusion#107]
I'm trying to use the core API as described in the project README:
```
#include <ElasticFusion.h>

int main(int argc, char** argv)
{
  Resolution::getInstance(640, 480);
  Intrinsics::getInstance(528, 528, 320, 240);
  std::cout << "Creating ElasticFusion object...\n";
  ElasticFusion eFusion;
  std::cout << "ElasticFusion object created successfully!\n";
  return 0;
}
```
My executable builds successfully, but it seems that creating an `ElasticFusion` object results in a segfault:
```
$ ./segfusion 
Creating ElasticFusion object...
Segmentation fault (core dumped)
```
Please advise.

**Comment by mp3guy** [comment]
You need to create an OpenGL context before creating the object as it uses OpenGL internally. You can do this whatever way you wish, using Pangolin is probably easiest given it's a dependency. 

pangolin::Params windowParams;
windowParams.Set("SAMPLE_BUFFERS", 0);
windowParams.Set("SAMPLES", 0);
pangolin::CreateWindowAndBind("Main", 1280, 800, windowParams);

Alternatively if you don't want an extra window, you can try EGL.
