### ISSUE TITLE
run with ground truth pose

### ISSUE THREAD

**Issue by zdczdcc** [mp3guy/ElasticFusion#109]
I'm going to run the ElasticFusion with ground truth pose given by the file livingRoom2.gt.freiburg from the ICL-NUIM.And i've convert the origin depth and rgb data to klg file by [png_to_klg](https://github.com/HTLife/png_to_klg).
When i run with the command `./ElasticFusion -l livingRoom2.klg`,it was ok.
But it was error(the reconstruction result was erroneous visibly) when i run with `./ElasticFusion -l livingRoom2.klg -p livingRoom2.gt.freiburg`.
What should i do to run correct with the `-p` option?Thanks a lot!

**Comment by mp3guy** [comment]
The format used for ground truth poses is not that of freiburg's, if you look at https://github.com/mp3guy/ElasticFusion/blob/master/GUI/src/Tools/GroundTruthOdometry.cpp you can see what format it expects.

**Comment by zdczdcc** [comment]
@mp3guy ,
thanks for your reply.I've been known about that.
