### ISSUE TITLE
Extracting odometry information

### ISSUE THREAD

**Issue by mjedmonds** [mp3guy/ElasticFusion#11]
Hi,

I was wondering if there is an easy way to access the odometry information produced by ElasticFusion.

I'm trying to evaluate it's performance and need to access the accuracy of the odometry and map. The map accuracy I should be able to extract from the saved map, but I can't seem to find an easy way to extract odometry.

Thanks

**Comment by mp3guy** [comment]
It writes out the pose graph when you close it, see here; https://github.com/mp3guy/ElasticFusion/blob/master/Core/src/ElasticFusion.cpp#L109

If you want to check the pose information while it's running, just look at the poseGraph class member.

You can also call getCurrPose() to get the current pose estimate.
