### ISSUE TITLE
Segmentation fault when trying to run higher resolutions 

### ISSUE THREAD

**Issue by AkshayHinduja** [mp3guy/ElasticFusion#113]
Hi!
I am using a stereo camera pair which is 752x480pi. If it is preprocessed to be 640x480 it works fine, however, on changing the resolution in maincontroller.cpp and passing full res images, the program runs into a segmentation fault. I aim to try even higher resolutions of 1280x1024. Is there something I am overlooking? I have also edited the logger accordingly. 

Backtrace for reference: 

Program received signal SIGSEGV, Segmentation fault.
_int_malloc (av=0x7ffff635b760 <main_arena>, bytes=704) at malloc.c:3700
3700	malloc.c: No such file or directory.
(gdb) bt

0  _int_malloc (av=0x7ffff635b760 <main_arena>, bytes=704) at malloc.c:3700
1  0x00007ffff601f7b0 in __GI___libc_malloc (bytes=704) at malloc.c:2891
2  0x00007ffff710dc39 in ?? () from /usr/lib/nvidia-352/libGL.so.1
3  0x00007ffff3121b00 in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.68
4  0x00007ffff3115c99 in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.68
5  0x00007ffff3118502 in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.68
6  0x00007ffff32557c5 in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.68
7  0x00007ffff3256d72 in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.68
8  0x00007ffff314edc4 in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.68
9  0x00007ffff314f5f7 in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.68
10 0x00007ffff3255d8e in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.68
11 0x00007ffff3264a18 in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.68
12 0x00007ffff2e25619 in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.68
13 0x00007ffff32673cd in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.68
14 0x00007ffff2e9e764 in ?? () from /usr/lib/nvidia-352/libnvidia-glcore.so.352.68
15 0x00007ffff7653a0a in Resize::vertex(GPUTexture*, Img<Eigen::Matrix<float, 4, 1, 0, 4, 1> >&) ()
   from /home/rpl/Documents/puneet/ElasticFusion-master/Core/build/libefusion.so
16 0x00007ffff7612f7e in Ferns::addFrame(GPUTexture*, GPUTexture*, GPUTexture*, Eigen::Matrix<float, 4, 4, 0, 4, 4> const&, int, float) () from /home/rpl/Documents/puneet/ElasticFusion-master/Core/build/libefusion.so
17 0x00007ffff762427a in ElasticFusion::processFerns() ()
   from /home/rpl/Documents/puneet/ElasticFusion-master/Core/build/libefusion.so
18 0x00007ffff7628000 in ElasticFusion::processFrame(unsigned char const*, unsigned short const*, long const&, Eigen::Matrix<float, 4, 4, 0, 4, 4> const*, float, bool) () from /home/rpl/Documents/puneet/ElasticFusion-master/Core/build/libefusion.so
19 0x0000000000416a8a in MainController::run() ()
20 0x0000000000417068 in MainController::launch() ()
21 0x0000000000412a1d in main ()

**Comment by pengpeng1997** [comment]
Could you please tell me how was your problem solved? I got the same problem with a resolution of 848*480 and I'm not sure what to change in the code.
