### ISSUE TITLE
Did ElasticFusion run correctly on my computer? (i7, Nvdia GT 1080)

### ISSUE THREAD

**Issue by lhanaf** [mp3guy/ElasticFusion#118]
I just downloaded the code and compiled it on ubuntu 16.04, and run it on dyson_lab.klg data.
At first it goes correctly and works well. After 6000 frames, the map begin to be distorted and the reconstructed results seems to be wrong, later part of the map got a wrong orientation like this picture:

![screenshot from 2017-10-20 17-13-55](https://user-images.githubusercontent.com/21303181/31814859-763d4fd2-b5bd-11e7-8140-cd595ac7f564.png)

**Comment by mp3guy** [comment]
I can't reproduce this unfortunately.

**Comment by lhanaf** [comment]
I just noticed that I'm using a wrong parameter for EFusion. Now I'm using the **default parameters** and get a map seems nice:

![elasticslam](https://user-images.githubusercontent.com/21303181/31849531-809e1f24-b676-11e7-9f82-b2b0852502a9.png)

Great work! However, there is still some in-consistences like monitors appeared multi-times. Can the results be better by choosing better parameters?

Thanks a lot for your help.


Best Regards

**Comment by mp3guy** [comment]
I just checked to see if there was a regression, but this doesn't happen for me.

**Comment by nonlinear1** [comment]
Me, too ! I use ElasticFusion with kinect2 to map my office. The same problem occures. I think there is something wrong with loop closure ?

**Comment by xingxing4182** [comment]
> Me, too ! I use ElasticFusion with kinect2 to map my office. The same problem occures. I think there is something wrong with loop closure ?



> Me, too ! I use ElasticFusion with kinect2 to map my office. The same problem occures. I think there is something wrong with loop closure ?

hi，when you use ElasticFusion with kinect2 to map your office the terminal output strs << "Your GPU \"" << dev << "\" isn't in the ICP Step performance database, please add it"?
