### ISSUE TITLE
Can elasticfusion reconstruct 3d objects not moving camera but by moving objects

### ISSUE THREAD

**Issue by choms0521** [mp3guy/ElasticFusion#120]
i want to know whether elasticfusion can reconstruct 3d objects by moving object on the turn table. 
it did try but when i turn object it failed tracking. are there any ideas?

**Comment by mp3guy** [comment]
I would guess the object is too small to constrain tracking, or there are other parts of the scene that are not moving with the turntable visible to the camera.
