### ISSUE TITLE
Problems with loop closure

### ISSUE THREAD

**Issue by 3dguy1** [mp3guy/ElasticFusion#123]
I am trying to reconstruct a room of 12mx10mx8m approximately and everytime I face a loop closure problem. I tried running ElasticFusion offline but no improvements. What are the parameters I need to look out for for improving loop closure. I tried global loop closure photometric threshold = 150 (default = 115) and Relative ICP/RGB tracking weight = 50 (default = 10).

**Comment by 3dguy1** [comment]
Any idea guys !!

**Comment by nonlinear1** [comment]
I was confronted with similar problem, It seems like no loop closure. Do you have any email? Maybe we can communicate with this problem.
