### ISSUE TITLE
GPUTest not work

### ISSUE THREAD

**Issue by andjsmile** [mp3guy/ElasticFusion#124]
Hi,man! Thanks in advanced. When I run ./Elasticfusion with my kinect, it tells me "Your GPU "GeForce GTX 1050 Ti" isn't in the ICP Step performance database, please add it",so I run GPUTest to get GPUConfig,but it tells me "terminate called after throwing an instance of 'std::runtime_error'
  what():  Rebuild Pangolin for PNG support. I reinstall Pangolin,but it not work.Can you help me?
"

**Comment by elliestath** [comment]
Hey, I have the same problem, any idea on that?

**Comment by andjsmile** [comment]
@elliestath  sorry,I have no idea to solve it, and I help someone tell me how to do it.

**Comment by GiorgioBullo** [comment]
hey, i found the solution. check this link:
https://github.com/stevenlovegrove/Pangolin/issues/290
