### ISSUE TITLE
Can we extract the camera poses from the .klg file

### ISSUE THREAD

**Issue by 3dguy1** [mp3guy/ElasticFusion#126]
I need to extract the the camera pose information from a .klg file. Can it be done by any means. I am aware of the convert_poses from https://github.com/martinruenz/dataset-tools . Will that serve the purpose? Or is there other means to extract pose information of the camera from a .klg file

**Comment by HTLife** [comment]
klg do not contain any pose information.

**Comment by Alice-kenan** [comment]
@LittleLampChen My .freiburg file is empty. Can you help me about this problem?
Looking forward to your reply.
