### ISSUE TITLE
How can efusion generate a pcd file when finished?

### ISSUE THREAD

**Issue by qixuxiang** [mp3guy/ElasticFusion#130]
Dear author,thanks for your awesome code share!

Efusion can generate a ply file which we can load in meshlab,
but how can we get the pcd file when we finished?

**Comment by wine3603** [comment]
@qixuxiang Hey, I think you can easily to use pcl tool : pcl_ply2pcd to transform ply to pcd. 
for the command lines, you can look at [here](http://www.pcl-users.org/transform-stl-file-to-pcd-file-td4034383.html)
