### ISSUE TITLE
PLY Export?

### ISSUE THREAD

**Issue by KoSv** [mp3guy/ElasticFusion#131]
Hey! Great work, Thanks!
How can I export a poincloud or PLY?
greetz!
(there is an option to save but nothing happens..)

**Comment by elliestath** [comment]
@KoSv if you press save then you should see a file with the extension .ply in your working directory, i.e. where you .klg file is.

**Comment by KoSv** [comment]
thanks!

**Comment by edith-langer** [comment]
Do you know a tool to visualize the reconstruction when saving it as ply? I know that meshlab can do that, but the surfels are not rendered with their radius, but just as points. I would really like to see the surfels with the radius.
Any ideas?

**Comment by KoSv** [comment]
perhaps: blender -> import ply -> particles -> use the particle color from "Col" in the vertex color tab?

**Comment by edith-langer** [comment]
@KoSv thanks for your answer! I'm not a blender expert. What you suggest is a fixed defined size for the radius? Or could I assign the real radius values of each surfel to a particle?

**Comment by KoSv** [comment]
@edith-langer what do you mean with "surfel" - > a vertex in the pointcloud?

**Comment by edith-langer** [comment]
@KoSv Yes, with surfel I mean a vertex in the reconstruction (having xyz-coordinates, color, confidence, radius, ...)

**Comment by KoSv** [comment]
@edith-langer ok... I din't know they have radius. does PLY support it?
if so, take a look in the "animation nodes" plugin for blender. you could grab the data ( if present as information in the pointcloud) and visualize it.
btw. blender has a python API. so anything custom is allowed! ;)
good luck!

**Comment by wine3603** [comment]
@edith-langer Hi, if you have PCL installed, you can use pcl_ply2pcd to make it to be pcd files and you can get the xyzrgb infos. for "surfel", since it is not a common format or unit, you have to go inside the codes and export it. 
BTW ply files can be visualized by CloudCompare and Meshlab.

**Comment by StoneCh168** [comment]
@edith-langer Try open3D! :D
