### ISSUE TITLE
Intrinsics for primesense asus 0609

### ISSUE THREAD

**Issue by YangLiu-DayDreammer** [mp3guy/ElasticFusion#14]
Hi, I have noticed that the default intrinsics is [528 528 320 240], but i am not using asus 0601. Does this intrinsics apply to 0609 too?

**Comment by mp3guy** [comment]
Those intrinsics are just a rough guess. They're probably safe to use, but if you want optimal performance you should calibrate your camera properly (e.g. with something like Calibu https://github.com/arpg/Calibu).

Even further you should estimate the warp from the RGB camera to the Depth Map, then capture unregistered sequences and apply the warp to the color image.
