### ISSUE TITLE
Cant scan a room. Loosing odometry at first instance

### ISSUE THREAD

**Issue by RajathSwaroop** [mp3guy/ElasticFusion#143]
![screenshot from 2018-04-16 18-16-50](https://user-images.githubusercontent.com/26526561/38843437-d4ae8f1e-41a3-11e8-9be9-ca880656bed7.png)
Hi,   I want to create a good 3-D map of my study room and I tried using Elastic Fusion to create a 3-D map using Intel Realsense R300 and D415 separately. With both the camera's the Elastic fusion just loses the odometry once I move the camera slightly from its position. It does not let me even record my table (loses odometry in first 20 seconds). Can you please help me use the right settings so I get good tracking. I am running the D400 at 60FPS (both depth and color). I have attached a sample of the map being generated to this message

**Comment by xielhjia** [comment]
do you solve this problem?
