### ISSUE TITLE
Can I get a mesh using Elastic Fusion

### ISSUE THREAD

**Issue by RajathSwaroop** [mp3guy/ElasticFusion#145]
Hi, I tried using Elastic Fusion with intel realsense D415 and it works great. However, it generates the point cloud map of the scene I record. I wish to get a mesh instead of point cloud. Is that possible??

**Comment by RajathSwaroop** [comment]
For a better loop closure should I have a lower inlier threshold or greater? Also can you explain how to covariance threshold works for loop closure (-cv).

**Comment by zc102241** [comment]
@RajathSwaroop i've also tried using ElasticFusion with intel realsense D435. I'm in trouble with "dev.set_frame_callback". There is no more such callback functions in librealsense2.
I tried to use the lambda function of rs2::sensor.run() ,but it failed. Could  u pls show some details of  ur Realsense2Interface.cpp file or give some hints about that?
Thanks  in advance

**Comment by zc102241** [comment]
solved. the problem is something about the stream profiles  of sensors : )

**Comment by LittleLampChen** [comment]
You can reconstruct a mesh by meshlab. 
however, the mesh is very noisy.

**Comment by lixz123007** [comment]
Do you get a mesh you want? I use meshlab to render-shaders-splatting to get something really like mesh.But i cannot save as mesh! There is no face. Any way to make a real mesh?

**Comment by densechen** [comment]
> @lixz123007 
You shoud export mesh in meshlab.

**Comment by lixz123007** [comment]
> > @lixz123007
> > You shoud export mesh in meshlab.

How to export mesh?After i splatting,it is no face.Or your meaning is using other reconstruct way (like Possion?）then export.

**Comment by densechen** [comment]
yes

**Comment by lixz123007** [comment]
> yes

well，i thought elasticfusion like BundleFusion can output mesh ...
But thanks!

**Comment by AN-1008** [comment]
I am wondering if the souce code of meshlab can be used.Then i can run the code of meshing in the terminal.
