### ISSUE TITLE
Can ElasticFusion work only with depth information?

### ISSUE THREAD

**Issue by jianjuan** [mp3guy/ElasticFusion#147]
I have succeed in running ElasticFusion online with X-tion. Now, I  am wondering that ElasticFusion can work successfully with only depth image, is there any easier way to achieve this or I have to change the source code deeply?
Thanks a lot! @mp3guy

**Comment by LittleLampChen** [comment]
According to the paper, color image is needed to pose estimation.

**Comment by mcooper12590** [comment]
You can do pose estimation with only the depth images using -i 100. You still need to supply an image however, but it can be a single color.
