### ISSUE TITLE
GPUTest build error on windows.

### ISSUE THREAD

**Issue by nargul90** [mp3guy/ElasticFusion#148]
I tried to build the GPUtest on windows and I get the error: 
Cannot open include file: 'sys/socket.h': No such file or directory
To my understanding this is not part of windows. Should I change something in the cpp file?

**Comment by hansonleelisong** [comment]
I have same question too, is there any solution?

**Comment by nargul90** [comment]
@hansonleelisong I couldn't find a solution but I asked my friend to run it on his Linux machine with 1080 ti (I have a 1080) and copied the values and rebuilt it and it worked (Of course, I had to rename the string to 1080).

**Comment by h1063135843** [comment]
define WIN32;NOMINMAX;WIN32_LEAN_AND_MEAN
