### ISSUE TITLE
Make error: libjpeg.so.8: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by lz199144** [mp3guy/ElasticFusion#150]
`[ 12%] Building CXX object CMakeFiles/ElasticFusion.dir/Main.cpp.o
[ 25%] Building CXX object CMakeFiles/ElasticFusion.dir/MainController.cpp.o
[ 37%] Building CXX object CMakeFiles/ElasticFusion.dir/Tools/GroundTruthOdometry.cpp.o
[ 50%] Building CXX object CMakeFiles/ElasticFusion.dir/Tools/LiveLogReader.cpp.o
[ 62%] Building CXX object CMakeFiles/ElasticFusion.dir/Tools/RealSenseInterface.cpp.o
[ 75%] Building CXX object CMakeFiles/ElasticFusion.dir/Tools/OpenNI2Interface.cpp.o
[ 87%] Building CXX object CMakeFiles/ElasticFusion.dir/Tools/RawLogReader.cpp.o
[100%] Linking CXX executable ElasticFusion
/usr/bin/ld: CMakeFiles/ElasticFusion.dir/Tools/RawLogReader.cpp.o: undefined reference to symbol 'jpeg_resync_to_restart@@LIBJPEG_8.0'
//usr/lib/x86_64-linux-gnu/libjpeg.so.8: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/ElasticFusion.dir/build.make:273: recipe for target 'ElasticFusion' failed
make[2]: *** [ElasticFusion] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ElasticFusion.dir/all' failed
make[1]: *** [CMakeFiles/ElasticFusion.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by whstarxu54** [comment]
I added "-ljpeg" as follows but the same error still exists. @lz199144 
set(CMAKE_CXX_FLAGS ${ADDITIONAL_CMAKE_CXX_FLAGS} "-O3 -msse2 -msse3 -Wall -std=c++11 -ljpeg ")

**Comment by EricLYang** [comment]
Add this line to GUI/src/CMakeLists.txt:
set(CMAKE_CXX_STANDARD_LIBRARIES -ljpeg)

**Comment by EricLYang** [comment]
> I added "-ljpeg" as follows but the same error still exists. @lz199144
> set(CMAKE_CXX_FLAGS ${ADDITIONAL_CMAKE_CXX_FLAGS} "-O3 -msse2 -msse3 -Wall -std=c++11 -ljpeg ")

Add this line to GUI/src/CMakeLists.txt:
set(CMAKE_CXX_STANDARD_LIBRARIES -ljpeg)

**Comment by YellowOrz** [comment]
> > I added "-ljpeg" as follows but the same error still exists. @lz199144
> > set(CMAKE_CXX_FLAGS ${ADDITIONAL_CMAKE_CXX_FLAGS} "-O3 -msse2 -msse3 -Wall -std=c++11 -ljpeg ")
> 
> Add this line to GUI/src/CMakeLists.txt: set(CMAKE_CXX_STANDARD_LIBRARIES -ljpeg)

also need to add ${CMAKE_CXX_STANDARD_LIBRARIES} in target_link_libraries
