### ISSUE TITLE
Assertion `findMode(width, height, fps) && "Sorry, mode not supported!"' failed.

### ISSUE THREAD

**Issue by glassxer** [mp3guy/ElasticFusion#152]
I am testing the ElasticFusion on GTX1070, things work fine with pronect in libfreenect2 also with NIviewer, and when I ran the Elastic Fusion in the GUI/build folder I got the error: 

> ElasticFusion: /home/vrlabone/Documents/ElasticFusion-master/GUI/src/Tools/OpenNI2Interface.cpp:119: OpenNI2Interface::OpenNI2Interface(int, int, int): Assertion `findMode(width, height, fps) && "Sorry, mode not supported!"' failed.
Aborted (core dumped)

I am using Cuda 9.2 and the driver for my graphic card is 396.18
Any idea?

**Comment by BruceWANGDi** [comment]
Hi, I met the same issue with you. Have you figured out any solution to solve this problem?
