### ISSUE TITLE
How does SO(3) pre-alignmen work?

### ISSUE THREAD

**Issue by hoangcuongbk80** [mp3guy/ElasticFusion#157]
Thanks for your great project. It works really well.
I am learning how your algorithm work. In the function `getIncrementalTransformation`, before applying ICP and RGBD integration, SO3 based on RGB images is used for initial orientation estimation? Could you explain how it works and which paper or any materials should I read to get more understanding about it?

`so3Step(lastNextImage[pyramidLevel],
                    nextImage[pyramidLevel],
                    imageBasis,
                    kinv,
                    krlr,
                    sumDataSO3,
                    outDataSO3,
                    jtj.data(),
                    jtr.data(),
                    &residual[0],
                    GPUConfig::getInstance().so3StepThreads,
                    GPUConfig::getInstance().so3StepBlocks);`

**Comment by mp3guy** [comment]
Essentially it's this - https://www.doc.ic.ac.uk/~ajd/Publications/lovegrove_davison_eccv2010.pdf
