### ISSUE TITLE
Error per point

### ISSUE THREAD

**Issue by YangLiu-DayDreammer** [mp3guy/ElasticFusion#16]
Hello, I am not sure whether my problem is meaningful. Can we extract the error information of each point? Like how can we distinguish stable points from unstable points.

Bests.

**Comment by mp3guy** [comment]
The 4th element of the Vector4f containing each point is the confidence. It is used when you download the map for example; https://github.com/mp3guy/ElasticFusion/blob/master/Core/src/ElasticFusion.cpp#L773
