### ISSUE TITLE
I have problems about how to run the dataset. Looking forward to your reply.

### ISSUE THREAD

**Issue by circleyuanquan** [mp3guy/ElasticFusion#170]
Sir, how did you make through in running klg demo? I just run the command
./ElasticFusion -l dyson_lab.klg
but error showed up:
Error: invalid texture reference: xxxx/convenience.cuh: 68
And I consulted to the answer which told me to
add "61" to Line24
But 61 is already there when I check that file
Would you mind to give me help with it?
So much appreciation!
#164 (comment)

**Comment by sunit1409** [comment]
following, same issue with nvidia 1080 ti.

**Comment by linmeeka** [comment]
Hi,have you solved this problem?I met same issue with nvidia RTX 2070, cuda 10.

**Comment by Alice-kenan** [comment]
You can try  make install after make.

**Comment by zss1995** [comment]
> Hi,have you solved this problem?I met same issue with nvidia RTX 2070, cuda 10.

Have you solved it? I met the same question

**Comment by linmeeka** [comment]
> > Hi,have you solved this problem?I met same issue with nvidia RTX 2070, cuda 10.
> 
> Have you solved it? I met the same question

I solved it by add this in CMAKELIST:
`set(CUDA_ARCH_BIN "75" CACHE STRING "Specify 'real' GPU arch to build binaries for, BIN(PTX) format is supported. Example: 1.3 2.1(1.3) or 13 21(13)")
set(CUDA_ARCH_PTX "" CACHE STRING "Specify 'virtual' PTX arch to build PTX intermediate code for. Example: 1.0 1.2 or 10 12")
`
and delete
`set(CUDA_ARCH_BIN "30 35 50 52 61" CACHE STRING "Specify 'real' GPU arch to build binaries for, BIN(PTX) format is supported. Example: 1.3 2.1(1.3) or 13 21(13)")
`
My GPU needs CUDA_ARCH_BIN 75

**Comment by zss1995** [comment]
> > > Hi,have you solved this problem?I met same issue with nvidia RTX 2070, cuda 10.
> > 
> > 
> > Have you solved it? I met the same question
> 
> I added this in CMAKELISTS:
> `set(CUDA_ARCH_BIN "75" CACHE STRING "Specify 'real' GPU arch to build binaries for, BIN(PTX) format is supported. Example: 1.3 2.1(1.3) or 13 21(13)") set(CUDA_ARCH_PTX "" CACHE STRING "Specify 'virtual' PTX arch to build PTX intermediate code for. Example: 1.0 1.2 or 10 12") `
> and deleted
> `set(CUDA_ARCH_BIN "30 35 50 52 61" CACHE STRING "Specify 'real' GPU arch to build binaries for, BIN(PTX) format is supported. Example: 1.3 2.1(1.3) or 13 21(13)") `
> My GPU needs CUDA_ARCH_BIN 75, using correct parameter solved my problem.

I have solved it by merely deleting
"set(CUDA_ARCH_BIN "30 35 50 52 61" CACHE STRING "Specify 'real' GPU arch to build binaries for, BIN(PTX) format is supported. Example: 1.3 2.1(1.3) or 13 21(13)") ",but thank you anyway.
