### ISSUE TITLE
Problem about running ./ElasticFusion -l dyson_lab.klg

### ISSUE THREAD

**Issue by circleyuanquan** [mp3guy/ElasticFusion#171]
I have removed 61 from CUDA_ARCH_BIN in CMake , but when I running ./ElasticFusion -l dyson_lab.klg error occured.
Error: invalid texture reference: /home/turtlebot/ElasticFusion/Core/src/Cuda/convenience.cuh:68
Looking forward to your reply, thank you very much!

**Comment by sunit1409** [comment]
you must be using 1060/70/80 for which  it is much required cuda arch

**Comment by sunit1409** [comment]
try with sudo

**Comment by zss1995** [comment]
> try with sudo

Hello, I met the same problem,and tried with sudo as you said,but error occured still.
