### ISSUE TITLE
Maximum number of total points

### ISSUE THREAD

**Issue by omaar97** [mp3guy/ElasticFusion#172]
Hello,

What determines the maximum possible number of generated total points? I'm using ElasticFusion for my own .klg file and it stops generating anything after it reaches 9437184 total points regardless of when it reaches that number, it doesn't crash it just continues to run and only the number of total ferns increases. Is there a way to let it generate more? or is it limited by the GPU power?

Thanks.

**Comment by Keudeugi** [comment]
Hope this helps you but I found that in the static variable MAX_VERTICES manages how many points you can register to global surfel map. Please refer GlobalModel class in Core library.
`const int GlobalModel::TEXTURE_DIMENSION = 3072;`
`const int GlobalModel::MAX_VERTICES = GlobalModel::TEXTURE_DIMENSION * GlobalModel::TEXTURE_DIMENSION;`
Note that 3072^2 = 9,437,184.
