### ISSUE TITLE
run very slow in live

### ISSUE THREAD

**Issue by xingxing4182** [mp3guy/ElasticFusion#173]
I am using the given test data set dyson_lab.klg log file very good. But the code runs very slow in live,the output is 
icpStepMap["GeForce GTX 1060 with Max-Q Design"] = std::pair<int, int>(64, 160);
rgbStepMap["GeForce GTX 1060 with Max-Q Design"] = std::pair<int, int>(128, 48);
rgbResMap["GeForce GTX 1060 with Max-Q Design"] = std::pair<int, int>(128, 400);
so3StepMap["GeForce GTX 1060 with Max-Q Design"] = std::pair<int, int>(128, 80);
 When i add it to GPUConfig.h,it don't work,What can be the probable cause?

**Comment by kemangjaka** [comment]
During ElasticFusion, the GPU is actually working?
