### ISSUE TITLE
Elastic fusion issues with 1080 ti / 1060 even after setting cuda_arch 61 

### ISSUE THREAD

**Issue by sunit1409** [mp3guy/ElasticFusion#174]
root@7c545fa63519:~# ./ElasticFusion/GUI/build/ElasticFusion -l /root/labelfusion/data/2017-05-04-01/trimmed_log.lcmlog -f
error: XDG_RUNTIME_DIR not set in the environment.
Error: unknown error: /root/ElasticFusion/Core/src/Cuda/containers/../convenience.cuh:68

I am using nvidia 1080 ti and 1060 machines. I am cloned the recent git repo which has cuda_arch 61 set. Can you please help me in this regard
@mp3guy  can you please help.

**Comment by gang007** [comment]
hi,I run ./ElasticFusion -l dyson_lab.klg with the same issue,can you help me ?

**Comment by sunit1409** [comment]
Install nvidia-docker 1 and you will be good to go.
