### ISSUE TITLE
More details on using ElasticFusion Core API

### ISSUE THREAD

**Issue by Richarizardd** [mp3guy/ElasticFusion#176]
I'm interested in using ElasticFusion without the GUI to get a dense point cloud of my video, but I'm having some trouble following the C code use the Core API on the dyson_lab.klg dataset. Was wondering if you could provide some instructions on how to put together a rough script to just use ElasticFusion without the GUI.

**Comment by yyxr75** [comment]
Hello,
Do you have any idea on how to use it?
