### ISSUE TITLE
sorry! The .klg format

### ISSUE THREAD

**Issue by maqiang6** [mp3guy/ElasticFusion#18]
sorry！

I want to follow the .klg format as your  annotate in the Logger::writeData。
Then,I have three questions
1. Both the depth and color image's width should be 640, height should be 480？
2. I use the uncompressed depth and color image to make a klg file.Then I use ./ElasticFusion -l  *.klg to run this file. The window only show the color image .It doesn't display the depth and point clound.
3.What is the uint of timestamp? is ms or us?

**Comment by hpp340** [comment]
Hi,
Which type of sensor do you use, Primesense or Kinect ? I have problems finding the sensor.

**Comment by maqiang6** [comment]
I use the KinectV1.0.  It can work on-line .You should have a libfreenect for KinectV1.0. Author created the project using OpenNI2 that doesn't supoort the Primesense.

**Comment by hpp340** [comment]
Yeah, I also use Kinect v1. I use build.sh to easy install ElasticFusion, and no error happened. Then I install libfreenect according to https://github.com/mp3guy/ElasticFusion/issues/15 , The standalone OpenNI2 programs can use the sensor but the ElasticFusion executable still can not find the sensor. How do you install it successfully?

**Comment by maqiang6** [comment]
Oh.I know what's your problem.
Have you read the file under libfreenect/OpenNI2-FreenectDriver/? You should copy your libfreenect-openni2.so and libfreenectDriver.so to your OpennI2 driver directory which is ElasticFusion-master/deps/OpenNI2/Bin/x64-Release/OpenNI2/Drivers/ for ElasticFusion project

**Comment by hpp340** [comment]
Thanks. But where is the  libfreenect-openni2.so ? I just find libfreenectDriver.so under lib/OpenNI2-FreenectDriver/.  I have already copy libfreenectDriver.so to ElasticFusion-master/deps/OpenNI2/Bin/x64-Release/OpenNI2/Drivers/ .

**Comment by mp3guy** [comment]
Hi, 

1. Yes, or whatever size the source PNGs are. 
2. This means the depth is not in the correct format. It should be unsigned short, unit of millimeters. 
3. Unit-less, just make it an increasing count (so frame one has timestamp 1, etc...). 

Tom

**Comment by stephane-lb** [comment]
@hpp340  Yes same issue here, did you find a solution ? Thanks

**Comment by mrkstt** [comment]
@maqiang6 have you successfully made .klg file from rgbd sequence?

**Comment by QinZiwen** [comment]
I use kinect v2, How should I run the GUI demo?

**Comment by fsrajer** [comment]
Just to inform anyone interested. I have coded my own Logger and I am creating valid .klg files. I am compressing depth like in Logger2 and I am using directly libjpeg to compress color. 

There were no problems. One thing to note, however, is that ElasticFusion is expecting BGR instead of RGB.

**Comment by mp3guy** [comment]
Just start ElasticFusion with -f

**Comment by fsrajer** [comment]
Thanks.

**Comment by martinruenz** [comment]
@fsrajer Is your logger open-source? Could you provide a link? Thanks! 
(How is it different from Logger2?)

**Comment by fsrajer** [comment]
@martinruenz I haven't made it opensource yet, but I think that would not be a problem.

It is a lightweight tool for saving stream from Intel RealSense camera into .klg file. It is a CMakeProject and was tested on Windows with Visual Studio. 
Dependencies:
* freeglut (visualization)
* librealsense (camera)
* zlib - optional (depth compression)
* libjpeg - optional (color compression)

Let me know if you would find it useful so that I know if I should make it opensource

**Comment by martinruenz** [comment]
@fsrajer Sounds awesome! I would definitely be interested.

**Comment by fsrajer** [comment]
OK, I have put it here. Feel free to do anything with it. I Hope it will be useful.
[https://github.com/fsrajer/LoggerRealSense](url)

**Comment by M1234Thomas** [comment]
Hello all,

I have a very basic question and sorry for that.
I do not understand how to run the program with the given .klg file.
Kindly help.

**Comment by HTLife** [comment]
@M1234Thomas  
See section 6 of https://github.com/mp3guy/ElasticFusion

**Comment by HTLife** [comment]
I'm also trying to write a converter for ICL-NUIM dataset.
The RGB part is fine, but depth data didn't works.

I read the depth file(.png) from ICL-NUIM by opencv function "cvLoadImage"
```
IplImage *imgDepth = 
            cvLoadImage(strAbsPathDepth.c_str(), 
                        CV_LOAD_IMAGE_UNCHANGED);
```
Each depth pixel occupy 2 bytes in IplImage array, it matches @mp3guy's comment about the depth pixel should be "unsigned short".

Therefore, I write the depth data to file directly without compression.
fwrite(imgDepth->imageData, imgDepth->imageSize, 1, logFile);

Anything wrong with my format? 
My code "https://github.com/HTLife/png_to_klg/blob/feature/main.cpp".
convertion code is start at line 35.

p.s. 
1.  I also tried to compress IplImage buffer then write to file, but I got the same result, not works.

**Comment by martinruenz** [comment]
@HTLife try something like this, it is working for me:
```
cv::Mat depth = imread(pathDepth, cv::IMREAD_UNCHANGED);
depth.convertTo(depth, CV_16UC1, 1000 * depthScale);
int32_t depthSize = depth.total() * depth.elemSize();
outStream.write((char*)&depthSize, sizeof(depthSize));
```
Where `depthScale` converts you depth input to [m].

**Comment by HTLife** [comment]
@martinruenz It works!!  Thanks for your reply.

**Comment by HTLife** [comment]
I developed a format converter to convert png sequence to .klg.
https://github.com/HTLife/png_to_klg/tree/master

Tested with both ICL-NUIM and TUM dataset.
Check it out!!

**Comment by wine3603** [comment]
@HTLife great ! can it handle the case that rgb and depth have different resolutions? (such as Kinect V2)

**Comment by HTLife** [comment]
@wine3603 The "png_to_klg" is not directly related to resolution issue of ElasticFusion.
"png_to_klg" simply read images and convert it to .klg format.

Possible solution could be done by resize images first.  
Converting both RGB and Depth image to 640*480 resolution, which is ElasticFusion default resolution taken by ASUS Xtion pro live.
Then feed resized image into "png_to_klg".

**Comment by zhangxiaoxuan1** [comment]
I've developed a program with OpenCV to capture depth/rgb images with RealSense sensors and generate the klg file for ElasticFusion/Kintinuous here: https://github.com/zhangxiaoxuan1/intel_image_grabber
