### ISSUE TITLE
Why not use CMAKE add_subdirectory to merge Core,  GPUTset, GUI to a single project

### ISSUE THREAD

**Issue by dogod621** [mp3guy/ElasticFusion#181]
In this way, if using visual studio, that will make build and modify this project more easier
![SOLUTION](https://user-images.githubusercontent.com/6807005/58343859-b510b800-7e86-11e9-9a49-de504a072fa4.jpg)

I post my version fixed CMake here
https://github.com/dogod621/ElasticFusion

**Comment by mp3guy** [comment]
There is a new branch coming soon that does this.
