### ISSUE TITLE
compileError 

### ISSUE THREAD

**Issue by LiliMeng** [mp3guy/ElasticFusion#19]
Hi,
     Thanks for the open source ElasticFusion. Currently it has the following installation errors. Thanks

/home/lci/workspace/ElasticFusion/Core/src/GlobalModel.cpp:265:43: error: no matching function for call to ‘Uniform::Uniform(const char [4], pangolin::OpenGlMatrix&)’
     program->setUniform(Uniform("MVP", mvp));
                                           ^

**Comment by mp3guy** [comment]
I would guess you haven't built Pangolin with Eigen support.

**Comment by LiliMeng** [comment]
Thanks a lot! It works and was compiled successfully!

**Comment by Godpeterliu** [comment]
@LiliMeng  I faced the same bug.  I try to build Pangolin with Eigen support by modifying the CMakelists.txt in the root dir of Pangolin.  I added the sentence "option(BUILD_PANGOLIN_EIGEN "Build support for Eigen matrix types" ON)" .  But, the change do not fix the bug.   How do you fix the bug?

**Comment by Godpeterliu** [comment]
@mp3guy  I faced the same bug. I try to build Pangolin with Eigen support by modifying the CMakelists.txt in the root dir of Pangolin. I added the sentence "option(BUILD_PANGOLIN_EIGEN "Build support for Eigen matrix types" ON)" . But, the change do not fix the bug. How do you fix the bug?

**Comment by 94zhaofang** [comment]
@mp3guy @LiliMeng How to built Pangolin with Eigen support ? Could you help me ? Thanks a lot !

**Comment by battlecry231** [comment]
@94zhaofang Maybe you need to create a symbolic link so that the library could be found:

`sudo ln -s /usr/lib/eigen3/Eigen /usr/lib/Eigen`
