### ISSUE TITLE
Cmake missing EFUSION_LIBRARY

### ISSUE THREAD

**Issue by Naor92** [mp3guy/ElasticFusion#191]
Hey everyone, I ran the build.sh script on a fresh clean install of Ubuntu 16.04 and everything seemed to install correctly until the very end when trying to build the GUI folder. Cmake spits out:

Could NOT find EFUSION (missing:  EFUSION_LIBRARY) 
Found SuiteSparse
SUITESPARSE_METIS_LIBRARY-NOTFOUND

Anyone experience this? Can't seem to find any EFusion Library

**Comment by apache8080** [comment]
I'm getting this error also on a Jetson AGX. Anybody have a solution for this?
