### ISSUE TITLE
how can I fix this problem? about make errror

### ISSUE THREAD

**Issue by SilentUniverse** [mp3guy/ElasticFusion#192]
`CMakeFiles/ElasticFusion.dir/MainController.cpp.o: In function `MainController::run()':
MainController.cpp:(.text+0xda4): undefined reference to `ElasticFusion::getFeedbackBuffers[abi:cxx11]()'
MainController.cpp:(.text+0xdc3): undefined reference to `FeedbackBuffer::RAW[abi:cxx11]'
MainController.cpp:(.text+0xdd7): undefined reference to `FeedbackBuffer::RAW[abi:cxx11]'
MainController.cpp:(.text+0xe40): undefined reference to `FeedbackBuffer::RAW[abi:cxx11]'
MainController.cpp:(.text+0xf35): undefined reference to `ElasticFusion::getFeedbackBuffers[abi:cxx11]()'
MainController.cpp:(.text+0xf54): undefined reference to `FeedbackBuffer::FILTERED[abi:cxx11]'
MainController.cpp:(.text+0xf67): undefined reference to `FeedbackBuffer::FILTERED[abi:cxx11]'
MainController.cpp:(.text+0xfd0): undefined reference to `FeedbackBuffer::FILTERED[abi:cxx11]'
MainController.cpp:(.text+0x196f): undefined reference to `ElasticFusion::getTextures[abi:cxx11]()'
MainController.cpp:(.text+0x1990): undefined reference to `ElasticFusion::getTextures[abi:cxx11]()'
CMakeFiles/ElasticFusion.dir/MainController.cpp.o: In function `MainController::launch()':
MainController.cpp:(.text+0x3b4b): undefined reference to `ElasticFusion::ElasticFusion(int, int, float, float, bool, bool, bool, float, float, float, float, bool, float, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/ElasticFusion.dir/MainController.cpp.o: In function `MainController::MainController(int, char**)':
MainController.cpp:(.text+0x402c): undefined reference to `Parse::arg(int, char**, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
MainController.cpp:(.text+0x4074): undefined reference to `Parse::arg(int, char**, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
MainController.cpp:(.text+0x40c0): undefined reference to `Parse::arg(int, char**, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
MainController.cpp:(.text+0x410c): undefined reference to `Parse::arg(int, char**, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
MainController.cpp:(.text+0x416e): undefined reference to `Parse::arg(int, char**, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
CMakeFiles/ElasticFusion.dir/MainController.cpp.o:MainController.cpp:(.text+0x420c): more undefined references to `Parse::arg(int, char**, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const' follow
CMakeFiles/ElasticFusion.dir/MainController.cpp.o: In function `loadProgramFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
MainController.cpp:(.text._ZL19loadProgramFromFileRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_S6_[_ZN3GUIC5Ebb]+0xd6): undefined reference to `Parse::shaderDir[abi:cxx11]() const'
MainController.cpp:(.text._ZL19loadProgramFromFileRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_S6_[_ZN3GUIC5Ebb]+0x172): undefined reference to `Parse::shaderDir[abi:cxx11]() const'
MainController.cpp:(.text._ZL19loadProgramFromFileRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_S6_[_ZN3GUIC5Ebb]+0x2f0): undefined reference to `Parse::shaderDir[abi:cxx11]() const'
MainController.cpp:(.text._ZL19loadProgramFromFileRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_S6_[_ZN3GUIC5Ebb]+0x382): undefined reference to `Parse::shaderDir[abi:cxx11]() const'
MainController.cpp:(.text._ZL19loadProgramFromFileRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_S6_[_ZN3GUIC5Ebb]+0x4ee): undefined reference to `Parse::shaderDir[abi:cxx11]() const'
CMakeFiles/ElasticFusion.dir/MainController.cpp.o:MainController.cpp:(.text._ZL19loadProgramFromFileRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_S6_[_ZN3GUIC5Ebb]+0x580): more undefined references to `Parse::shaderDir[abi:cxx11]() const' follow
CMakeFiles/ElasticFusion.dir/MainController.cpp.o: In function `GUI::GUI(bool, bool)':
MainController.cpp:(.text._ZN3GUIC2Ebb[_ZN3GUIC5Ebb]+0x98b): undefined reference to `GPUTexture::RGB[abi:cxx11]'
MainController.cpp:(.text._ZN3GUIC2Ebb[_ZN3GUIC5Ebb]+0x9a7): undefined reference to `GPUTexture::DEPTH_NORM[abi:cxx11]'
MainController.cpp:(.text._ZN3GUIC2Ebb[_ZN3GUIC5Ebb]+0xddc): undefined reference to `GPUTexture::DEPTH_NORM[abi:cxx11]'
MainController.cpp:(.text._ZN3GUIC2Ebb[_ZN3GUIC5Ebb]+0xdef): undefined reference to `GPUTexture::RGB[abi:cxx11]'
CMakeFiles/ElasticFusion.dir/Tools/LiveLogReader.cpp.o: In function `LiveLogReader::getFile[abi:cxx11]()':
LiveLogReader.cpp:(.text+0x33e): undefined reference to `Parse::baseDir[abi:cxx11]() const'
/usr/local/lib/libefusion.so: undefined reference to `pangolin::PathParent(std::string const&, int)'
/usr/local/lib/libefusion.so: undefined reference to `pangolin::FileExists(std::string const&)'
/usr/local/lib/libefusion.so: undefined reference to `pangolin::PathExpand(std::string const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/ElasticFusion.dir/build.make:270: recipe for target 'ElasticFusion' failed
make[2]: *** [ElasticFusion] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/ElasticFusion.dir/all' failed
make[1]: *** [CMakeFiles/ElasticFusion.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
`
I use ElasticFusion wtih Ubuntu18.04 .
And it appears in /ElasticFusion/GUI/build  when "make ". 
Anyone experience this?How can I do this?Please help me.

**Comment by zheng-xiao** [comment]
Hi, Did you solve it?
I have the same issue.
