### ISSUE TITLE
ElasticFusion/GUI/src/Tools/LcmLogReader.cpp:98:15: error: 'images_t' is not a member of 'bot_core'

### ISSUE THREAD

**Issue by acidtonic** [mp3guy/ElasticFusion#195]
ElasticFusion/GUI/src/Tools/LcmLogReader.cpp:98:15: error: 'images_t' is not a member of 'bot_core'

Did I miss something? image_t is there? Did libbot2-core change something? Any ideas?

**Comment by acidtonic** [comment]
Self-solved....

I was missing openni2-camera-lcm while following another build guide. Had OpenNI2 but not all of it.

**Comment by GiuliaP** [comment]
@acidtonic I have exactly the same problem, could you explain how you solved it? 

Also, why libbot2-core is not indicated as a dependency of ElasticFusion? Which repository should we use for it?

Thank you very much!!!
