### ISSUE TITLE
add icp

### ISSUE THREAD

**Issue by LiliMeng** [mp3guy/ElasticFusion#20]
Hi,

   Thanks for your code, it works pretty good! But when execution, such as $./ElasticFusion -l file.klg, it has the following displays. How to add the ICP step? Thanks a lot!

Your GPU "Quadro K1000M" isn't in the ICP Step performance database, please add it
Your GPU "Quadro K1000M" isn't in the RGB Step performance database, please add it
Your GPU "Quadro K1000M" isn't in the RGB Res performance database, please add it
Your GPU "Quadro K1000M" isn't in the SO3 Step performance database, please add it

**Comment by mp3guy** [comment]
Run the included GPUTest program and it will output the code you can paste into this class https://github.com/mp3guy/ElasticFusion/blob/master/Core/src/Utils/GPUConfig.h

**Comment by LiliMeng** [comment]
Thanks a lot! It works!

**Comment by zry656565** [comment]
@mp3guy 
Should I create a PR to add my code generated by GPUTest for GeForce 860M?

**Comment by mp3guy** [comment]
Not necessary, but if you want I'll merge it.
