### ISSUE TITLE
error while using  SurfReg 

### ISSUE THREAD

**Issue by canglangzhige** [mp3guy/ElasticFusion#204]
Do I have to use 1.7, is it ok with 1.10? I get an error during make:
/usr/bin/ld: CMakeFiles/SurfReg.dir/SurfReg.cpp.o: undefined reference to symbol 'pthread_condattr_setclock@@GLIBC_2.3.3'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
How can this be resolved?

**Comment by JannisEgelhof** [comment]
Maybe the solution here:
#161

**Comment by canglangzhige** [comment]
Thank you very much, this is very helpful and I have solved it.
