### ISSUE TITLE
Can it run on Ubuntu18.04？

### ISSUE THREAD

**Issue by Gatsby23** [mp3guy/ElasticFusion#208]
I have test the algorithm on Ubuntu18.04, there are some problem about the CUDA like this
![Screenshot 2020-05-19 18:36:57](https://user-images.githubusercontent.com/18000675/82316695-c93ab700-99ff-11ea-8e65-e542f4492508.png)
I have alread Remove 61 from the CUDA_ARCH_BIN, but it still show the same wrong information.

**Comment by a333klm** [comment]
use #161

**Comment by Gatsby23** [comment]
> use #161

OK,Thanks!
