### ISSUE TITLE
error occurred when running the example

### ISSUE THREAD

**Issue by HanochZzhou** [mp3guy/ElasticFusion#210]
Hi, thanks for sharing your great work. There is an error when I ran the example:
./ElasticFusion -l ../.. dyson_lab.klg
ElasticFusion: /home/zh/Documents/ElasticFusion/GUI/src/Tools/RawLogReader.cpp:31: RawLogReader::RawLogReader(std::__cxx11::string, bool): Assertion `tmp' failed.
Aborted (core dumped)

All installations have been successful.
Could you help me? Thanks a lot~

**Comment by lifuling20162366** [comment]
Hello, how did you solve this problem?

**Comment by HanochZzhou** [comment]
@lifuling20162366  I set the wrong file path. Just make sure your file path is correct~
