### ISSUE TITLE
Unable to find SuiteSparse

### ISSUE THREAD

**Issue by gaotao19890725** [mp3guy/ElasticFusion#212]
gaotao@gaotao-desktop:~/data/ElasticFusion/Core/src/build$ cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "9.0") 
CMake Error at FindSuiteSparse.cmake:115 (MESSAGE):
  Unable to find SuiteSparse
Call Stack (most recent call first):
  CMakeLists.txt:9 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/gaotao/data/ElasticFusion/Core/src/build/CMakeFiles/CMakeOutput.log".
See also "/home/gaotao/data/ElasticFusion/Core/src/build/CMakeFiles/CMakeError.log".

**Comment by gaotao19890725** [comment]
Dear author, I am trying to realize the project in Ubuntu 18.04 (TX2) but I meet some problems about SuiteSparse. According to your suggestion, I sudo apt-get install libsuitesparse, when I cmake ans then the above error occurs. Can you share your wisdom with me and give me some suggestions. Thank you a million.

**Comment by gaotao19890725** [comment]
Dear author, I am trying to realize the project in Ubuntu 18.04 (TX2) but I meet some problems about SuiteSparse. According to your suggestion, I sudo apt-get install libsuitesparse-dev, when I cmake and then the above error occurs. Can you share your wisdom with me and give me some suggestions. Thank you a million.

**Comment by BruceWANGDi** [comment]
@gaotao19890725 Hi, I met the same issue with you. My CUDA is also 9.0. Have you figured out any solution to solve this problem?

**Comment by BruceWANGDi** [comment]
@gaotao19890725 I figured out a method to solve this issue. Just run the order below: 'sudo apt-get install libsuitesparse-dev', and then cmake again. I hop this can help you

**Comment by wenjinshi** [comment]
I also met the similar issue:

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr (found version "10.1") 
-- Found SuiteSparse
-- CUDA NVCC target flags: -gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_61,code=sm_61
-- Configuring done
-- Generating done
-- Build files have been written to: /home/csl/wenjin/ElasticFusion/Core/build

but it can found SuiteSparse,how can I solve my issue?
