### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by gaotao19890725** [mp3guy/ElasticFusion#214]
At first, I successfully build the ElasticFusion, and when I run the command ./ElasticFusion -l dyson_lab.klg, it succeeds. But when I install the realsense2,  I run ./ElasticFusion or ./ElasticFusion -l dyson_lab.klg, the following error occurs:

Segmentation fault (core dumped)

Very strange, can you give me some concrete suggestion to modify it. Thanks a million.

**Comment by heruiyuan** [comment]
Have you solved this problem? I have the same issue.

**Comment by Viky397** [comment]
Same issue

**Comment by tfy14esa** [comment]
Hi @Viky397,
Were you able to resolve the issue? I am facing the same issue

**Comment by mp3guy** [comment]
I would suggest building the binary in debug mode and then using gdb to get a stack trace, as a starting point.

**Comment by tfy14esa** [comment]
> I would suggest building the binary in debug mode and then using gdb to get a stack trace, as a starting point.

Hi @mp3guy 
Thanks a lot for your response. See this thread for a complete stack trace: https://github.com/mp3guy/ElasticFusion/issues/222
