### ISSUE TITLE
OpenGL Error: XX (1280)

### ISSUE THREAD

**Issue by heiwuya-heiwuya** [mp3guy/ElasticFusion#215]
Hello, When I ran "run_prep" in Labelfusion, I met always this error. My laptop ist Ubuntu 16.04, GTX1660Ti(Driver: 418.74, Cuda 10.0).

Anyone can help me ?  Thanks a lot  !!!

" root@heiwuya:~/labelfusion/LabelFusion_Sample_Data/logs/test# run_prep
Running pre-processing stage...
rewind is: 0
GLSL Shader compilation failed: /root/ElasticFusion/Core/src/Shaders/draw_global_surface.vert:
0:19(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

GLSL Shader compilation failed: /root/ElasticFusion/Core/src/Shaders/draw_global_surface.geom:
;
GLSL Shader compilation failed: /root/ElasticFusion/Core/src/Shaders/draw_global_surface_phong.frag:
0:19(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES
.....
.....
OpenGL Error: XX (1280)
In: /root/ElasticFusion/Pangolin/include/pangolin/gl/gl.hpp, line 192
OpenGL Error: XX (1281)
In: /root/ElasticFusion/Pangolin/include/pangolin/gl/gl.hpp, line 192
Segmentation fault (core dumped)
"

**Comment by BruceWANGDi** [comment]
@heiwuya-heiwuya  Hi, I met the same issue with you, have you figured out any solution to solve this problem?
