### ISSUE TITLE
error occurred when running the example dyson_lab.klg

### ISSUE THREAD

**Issue by lifuling20162366** [mp3guy/ElasticFusion#216]
Hi, thanks for sharing your great work. There is an error when I ran the example:
./ElasticFusion -l ../.. dyson_lab.klg
ElasticFusion: /home/cqu/Downloads/ElasticFusion-master/GUI/src/Tools/RawLogReader.cpp:78: void RawLogReader::getCore(): Assertion `tmp' failed.
Aborted (core dumped)

In fact, it can run for a while, but after that, it will exit the running interface, and then the above error will appear.

All installations have been successful.
Could you help me? Thanks a lot~

**Comment by Viky397** [comment]
Were you able to solve this? I get this error when I try to run my own .klg file
