### ISSUE TITLE
SO3 pre-alignment

### ISSUE THREAD

**Issue by duanzhimin14** [mp3guy/ElasticFusion#223]
What is SO3 pre-alignment, can anyone tell me what it does？

**Comment by mhayoz** [comment]
It is used to estimate camera rotation only. The estimate is then used as an initialization for ICP and RGB pose estimation. Rotation estimation seems to be more robust in the presence of fast camera movements and blur. 
look at this source: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.175.2455&rep=rep1&type=pdf
