### ISSUE TITLE
Fit it on realsense l515 device

### ISSUE THREAD

**Issue by Sylvia6** [mp3guy/ElasticFusion#228]
I'm adapting Elasticfusion  to the l515 device of realsense. At present, the device can be detected, but there are some problems with my Elasticfusion result.

Considering that the RGB resolution of the l515 device is a fixed combination of 1280 * 720 and the depth resolution of 640 * 480, I want to know how to make elasticfusion work correctly. Can u help me?

**Comment by Sylvia6** [comment]
Here is my elasticfusion result:
![image](https://user-images.githubusercontent.com/32163681/113964334-e1a50180-985d-11eb-9af7-221283780857.png)

As the picture shows, the rgb and depth result is dismatched with the core interface

**Comment by YangXJ95** [comment]
Hello @Sylvia6, did you solve this mismatch problem in the end?
