### ISSUE TITLE
Hi, when I run ICL-NUIM dataset, it is wried the ape rmse is so big compared with the results shown in paper. I wonder what flag or parameter should be set. Thanks.

### ISSUE THREAD

**Issue by ZhouXiner** [mp3guy/ElasticFusion#232]

**Comment by ZhouXiner** [comment]
The command is:
/ElasticFusion -icl -l '/media/zhouxin/752f5c44-4792-4b59-b2a9-8c249bd10148/ICL/klg/livingRoom0.klg'  -d 100

**Comment by ZhouXiner** [comment]
Also when I try to make the y axis value in trajectory to -y, the rmse is better. Why?

**Comment by ZhouXiner** [comment]
when I

**Comment by wenjinshi** [comment]
我运行elasticfusion有其他的问题，可以问问你吗？

**Comment by ZhouXiner** [comment]
> 我运行elasticfusion有其他的问题，可以问问你吗？
啥事你说

**Comment by zhuisa** [comment]
@ZhouXiner 在与ElasticFusion进行对比时，我应该依赖自己实验得出的数据，还是直接使用论文中提供的结果呢？因为我发现无法复现出与ElasticFusion论文中完全一致的数据。
