### ISSUE TITLE
Issue with the Eigen dependency

### ISSUE THREAD

**Issue by aicioara** [mp3guy/ElasticFusion#27]
Hello. I was wondering what version of the Eigen Library (>= x) is required for building the core. 

I see in the install command that `libeigen3-dev` is stated. However, this extra step was required 

```bash
ln -sf /usr/include/eigen3/Eigen /usr/include/Eigen
```

Now, I am having some compatibility issues 

```
Core/src/IndexMap.cpp:164:42: error: invalid use of incomplete type ‘const struct Eigen::internal::inverse_impl<Eigen::Matrix<float, 4, 4> >’
     Eigen::Matrix4f t_inv = pose.inverse();
                                          ^
```

I was assuming it's from the library used.

**Comment by mp3guy** [comment]
Have you built Pangolin with Eigen supoprt?

**Comment by aicioara** [comment]
You are correct. It is worth mentioning this in FAQ, since the error is misleading.

**Comment by mp3guy** [comment]
This is already mentioned in the instructions; "It is important to build Pangolin last so that it can find some of the libraries it has optional dependencies on."
