### ISSUE TITLE
Works with Microsoft kinect v2?

### ISSUE THREAD

**Issue by ShunIto2015** [mp3guy/ElasticFusion#29]
I have a Microsoft Kinect V2 sensor and will ElasticFusion work with this version?
I've read that the Performance is much better than the kinect v1 and others(XTION LIVE...)

**Comment by mp3guy** [comment]
There is no official support, but you may have success following this approach; https://github.com/mp3guy/Kintinuous/issues/5#issuecomment-215896353

**Comment by ShunIto2015** [comment]
Thank you so much.I'll give it a try.

**Comment by alexsmartens** [comment]
@ShunIto2015 did you make ElasticFusion work with Kinect v2? If so, could you share your experience?
