### ISSUE TITLE
Does it worked for windows 7 Operating System?

### ISSUE THREAD

**Issue by kerrylev** [mp3guy/ElasticFusion#37]
You have did a great work, it's amazing! And I was wondering if there had been any more consideration for windows OS, all the dependencies can be build in windows OS. Do you ever have a try ?

**Comment by mp3guy** [comment]
I haven't tried it myself, but I've heard that it builds ok on Windows.

**Comment by fsrajer** [comment]
@kerrylev, check my pull request.

**Comment by xiaozhuka** [comment]
I have successfully compiled on Windows with VS 2013, but there always some unkonwn error when running with ICL-NUIM dataset.

**Comment by fsrajer** [comment]
I didn't run it with that dataset. Feel free to patch my changes.

**Comment by LittleLampChen** [comment]
@fsrajer I have try to compile core code in windows, but failed with the error 
""
![image](https://user-images.githubusercontent.com/14089191/46061888-b0322200-c19a-11e8-859d-5e9ce484623f.png)
