### ISSUE TITLE
Could you please share other .klg files

### ISSUE THREAD

**Issue by mrkstt** [mp3guy/ElasticFusion#39]
Hi Thomas,

Could you please share other .klg files, e.g. copyroom dataset from Qianyi et al's ?.
I want to compare the result to my existing system.

Thanks.

**Comment by mp3guy** [comment]
You can convert the logs from Qianyi to the klg format quite easily; https://github.com/mp3guy/ElasticFusion/issues/18#issuecomment-223853284

**Comment by Viky397** [comment]
Question: I have .klg files from my own dataset. However, when I run ElasticFusion -l <my.klg>, the GUI opens up and I can see my frames at the bottom. However, no points appear and nothing seems to be happening. Any help is appreciated, thanks!
