### ISSUE TITLE
Single object reconstruction

### ISSUE THREAD

**Issue by mrkstt** [mp3guy/ElasticFusion#40]
Hi,

Is there any specific parameters should be enabled to reconstruct single object?. I tested this [data](http://redwood-data.org/3dscan/dataset.html?c=motorcycle&i=5737).

Thanks.

**Comment by mrkstt** [comment]
I guess the data is not properly recorded, I test the "burghers of calais" from Qianyi, worked nice.
Any idea?

Thanks.

**Comment by mp3guy** [comment]
For outside in type reconstruction of small objects like that a TSDF-based system is probably a better way to go.
