### ISSUE TITLE
My work circumstance is windows 7, so I use Xmanager5 to connect a server installed ubuntu 14,04 

### ISSUE THREAD

**Issue by ManyuChang** [mp3guy/ElasticFusion#41]

**Comment by ManyuChang** [comment]
@NeXT1995  You cannot use software to connect the server which runs the SLAM. You just can see the result on the server's screen.

**Comment by NeXT1995** [comment]
I configured the driver, but when I ran SLAM,I meet,

terminate called after throwing an instance of 'std::runtime_error'
  what():  Pangolin X11: Unable to retrieve framebuffer options

I revised it（https://blog.csdn.net/JAYSITE/article/details/80224750） according to this opinion.

But the problem persists.
