### ISSUE TITLE
Pangolin X11: Invalid GLX version. Require GLX >= 1.3

### ISSUE THREAD

**Issue by ManyuChang** [mp3guy/ElasticFusion#42]
My work circumstance is windows 7, so I use Xmanager5 to connect a server installed ubuntu 14,04. When I run the command:" ./ElasticFusion -l dyson_lab.klg", displaying fellowing issue:
terminate called after throwing an instance of 'std::runtime_error'
  what():  Pangolin X11: Invalid GLX version. Require GLX >= 1.3

**Comment by mp3guy** [comment]
I would guess Xmanager5 doesn't give OpenGL a valid context.
