### ISSUE TITLE
How to save estimated camera pose?

### ISSUE THREAD

**Issue by JunshengFu** [mp3guy/ElasticFusion#44]
Thanks for the great work!

I am new to ElasticFusion, and I have a basic question: in order to compare with the ground truth camera pose, how can I export the estimated camera pose by ElastidcFusion?

e.g. after running the sample data, if I click "save", the reconstructed point cloud will be exported, but how can I export the camera poses?  
$./ElasticFusion -l dyson_lab.klg

Thanks!

**Comment by mp3guy** [comment]
If you look at the destructor the poses are written out there; https://github.com/mp3guy/ElasticFusion/blob/master/Core/src/ElasticFusion.cpp#L98
