### ISSUE TITLE
ICP/RGB tracking weight 

### ISSUE THREAD

**Issue by JunshengFu** [mp3guy/ElasticFusion#45]
Is it possible to set different "ICP/RGB tracking weights" for different frames?
-i : Relative ICP/RGB tracking weight 

Or, do you have any advice for me to achieve this? Thanks!

**Comment by mp3guy** [comment]
It is possible yes. Make the appropriate call to https://github.com/mp3guy/ElasticFusion/blob/master/Core/src/ElasticFusion.h#L137
