### ISSUE TITLE
Hello, Where is Online global dense surface optimisation option in GUI?

### ISSUE THREAD

**Issue by kimjinyam** [mp3guy/ElasticFusion#56]
here the video
https://www.youtube.com/watch?v=XySrhZpODYs
0:18
Online global dense surface optimisation
and deviated point clouds angle to correct point cloud angle.

But i can't find that option in GUI

**Comment by mp3guy** [comment]
It's automatic

**Comment by kimjinyam** [comment]
Thanks. reply
maybe i must more practice.
