### ISSUE TITLE
GTX 1080 parameters

### ISSUE THREAD

**Issue by YangLiu-DayDreammer** [mp3guy/ElasticFusion#57]
Hello, recently I have installed GTX 1080 and want to add parameter of it in to GPUconfig. When I try GPUTest it returns:
Searching for the best thread/block configuration for your GPU...
Error: invalid device function: RGBD_SLAM_PKG_20161004/ElasticFusion/Core/src/Cuda/convenience.cuh:68
How can I solve this?
Thank you

**Comment by HTLife** [comment]
Did you successfully run sample dataset?

Maybe your problem is related to mine (https://github.com/mp3guy/ElasticFusion/issues/55).

**Comment by YangLiu-DayDreammer** [comment]
Thank you very much. It perfectly solve my problem. I think for GTX 1060/1070/1080 and other future GPUs we should modify CMakeLists to adjust.

**Comment by zssjh** [comment]
@HTLife I git the newest version, and the cmakelist.txt have been modified(listing 61),but I still face the problem, what is the reason of the problem? many many thanks!

**Comment by luruibo1995** [comment]
The Compute Capability of your GPU is somewhat important. My GPU is 2080 and I have to update cuda to the 10+, add 75 in the CMakeLists.txt just like  #55 and modify the  function __shfl_down to __shfl_down_sync , the mask i choice is 0xFFFFFFFF, you can refer https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#synopsis and https://stackoverflow.com/questions/50639194/shfl-down-and-shfl-down-sync-give-different-results.
