### ISSUE TITLE
How to make 3D output with RGB color

### ISSUE THREAD

**Issue by amiltonwong** [mp3guy/ElasticFusion#6]
Hi, @mp3guy ,

Your work is impressive. 
And I obtain first trial result as follows:
https://www.dropbox.com/s/89xs9lgknq5lr4p/result.png?dl=0

As the 3D output doesn't contain RGB-color, how could I make 3D output with RGB color using ElasticFusion like your demo?
https://www.youtube.com/watch?v=XySrhZpODYs

Best regards,
Milton

**Comment by mp3guy** [comment]
Check the "Draw colors" option on the left hand side of the GUI
