### ISSUE TITLE
how to run without loop closure

### ISSUE THREAD

**Issue by nkwangyh** [mp3guy/ElasticFusion#60]
I've run the demo with "-o" and it seems that loop closure is closed. Am I right or not? Can you help me?

**Comment by mp3guy** [comment]
-o turns off explicit loop closure, the loop might still close implicitly.

**Comment by nkwangyh** [comment]
Thank you very much. So is there any way to disable loop closure completely? I think I've made it by not loading DBoW vocabulary file and not performing online deformation in Kintinuous. But I don't know how to do in ElasticFusion.

**Comment by mp3guy** [comment]
-o turns off explicit loop closure in ElasticFusion
