### ISSUE TITLE
Elastic fusion runs really slow

### ISSUE THREAD

**Issue by M1234Thomas** [mp3guy/ElasticFusion#62]
Hello,

I have built the code in visual studio 2013 with GPU NVIDIA GeForce GTX 750 Ti and I am using the given test data set dyson_lab.klg log file. But the code runs very slow on my machine. 
What can be the probable cause?

**Comment by mp3guy** [comment]
Your GPU is nowhere near good enough. The 750 Ti only puts out 1305.6 GFLOPS, and you need at least 3500 GFLOPS. In addition to this, if you're running on Windows, you have to pay extra over head when running CUDA kernels due to the WDDM.
