### ISSUE TITLE
load a .ply map and just estimate the pose on the map?

### ISSUE THREAD

**Issue by egeldres** [mp3guy/ElasticFusion#66]
Hello, thank you for opening this huge project.

Is there any way to load a saved .ply map, and then run the localization module, just to have the geometric and photometric pose estimation? without continously map the enviroment?

Many thanks in advance

**Comment by mp3guy** [comment]
This is entirely possible, the code for it just needs to be written to load the surfels back into the GlobalModel class. You'll also want to save/load the Fern database too in order to relocalise.

**Comment by egeldres** [comment]
Many thanks for your quick answer, and for the important advice about the Ferns.
