### ISSUE TITLE
GPU memory

### ISSUE THREAD

**Issue by Minotaur-CN** [mp3guy/ElasticFusion#7]
Hi, 

The ElasticFution pre-malloc GPU memory is 1800M, but only about 400M memory used in the program. How can I config the GPU memory allocate to reduce the memory pre-malloc. Less GPU memory pre-allocate could reduct the GPU requirement.
Is that in GPUConfig.h?

Thanks very much!

Regards

**Comment by mp3guy** [comment]
You can lower this value; https://github.com/mp3guy/ElasticFusion/blob/master/Core/src/GlobalModel.cpp#L21

This does however restrict the number of surfels in the map, unless you implement dynamic VBO allocation/resizing.
