### ISSUE TITLE
Does this project support intel Realsense R200 ?

### ISSUE THREAD

**Issue by HolaMirai** [mp3guy/ElasticFusion#72]
hi:
I`m wondering whether this project supports intel Realsense R200 since there is an optional install of librealsense ?  I have build this project successed and installed the librealsense, my paltform is Ubuntu 14.04 and x64, but when i run the executable application ElasticFusion, the application told me that there is no devices found. so Does this project support intel Realsense R200 ? thank you in advance.

**Comment by zhangduoshou** [comment]
I have the same problem

**Comment by zhangduoshou** [comment]
hello，have ur problem been solved？
