### ISSUE TITLE
CUDA setup errors? 

### ISSUE THREAD

**Issue by Skybutter0** [mp3guy/ElasticFusion#74]
We have been trying to use the build.sh script to build the package, but it seems like we are having issues with CUDA, or something along the lines of that. 
We have been using Ubuntu 15.04, with Nvidia driver 352 and a GTX 980. 
I think the main issue here is "compute error 61"? 
Any help would be much appreciated. 
Thank you, 
-George and Zoe

[Attached](https://docs.google.com/document/d/1GjwAkdsScMX-nEDlAu4TtZCcl3y7TYCDG7bfFxdl6jc/edit?usp=sharing) are the errors.

**Comment by mp3guy** [comment]
Remove 61 from the CUDA_ARCH_BIN CMake entry
