### ISSUE TITLE
How to adjust parameters to trigger "Global loop closure"?

### ISSUE THREAD

**Issue by HTLife** [mp3guy/ElasticFusion#75]
Currently I'm working on applying TUM "fr2/360_kidnap" to ElasticFusion.  However, loop could not been detected.  (Kintinuous could detect loop but the map is broken.)

If I want to get a map with complete reconstruction result and loop closure, what would you guys suggest?

# Here are my experinment parameters and result
## ElasticFusion
`./ElasticFusion -l '/dataset/tum/rgbd_dataset_freiburg2_360_kidnap/scale_0_0002.klg' -ftf -d 12 -c 4 -ft 0.1`
 - Do frame-to-frame RGB tracking.
 - Cutoff distance = 12m
 - Surfel confidence threshold = 4
 - Fern encoding threshold = 0.1

Final result screenshot:
![screenshot from 2017-02-19 16-31-54](https://cloud.githubusercontent.com/assets/4699179/23100730/539116c6-f6c3-11e6-9469-d98acc7fdf9f.png)
Video: https://youtu.be/PWe2Cziccw8

I provide my .klg file here for result reproduce. (ftp://ccurvl.csie.io/slam_exp/)

I did both ElasticFusion and Kintinuous on TUM "fr2/360_kidnap"
  - ElasticFusion: [good] map reconstruction,  [bad] loop detection
  - Kintinuous: [good] loop detection, [bad] map reconstruction (maybe didn't find the right voxel threshold or other related...)

I also tried the instruction in https://github.com/mp3guy/ElasticFusion/issues/21 to adjust some parameters, but loop detection still don't work with TUM kidnap dataset.

---
## Kintinuous
Seems like depth cutoff issue, still finding related code or fix this problem.
`./build/Kintinuous -v ./vocab.yml.gz -l /rgbd_dataset_freiburg2_360_kidnap/scale_0_0002.klg   -ri -fl -od -dg 0.1 -cw 20`
![screenshot from 2017-02-19 17-49-24](https://cloud.githubusercontent.com/assets/4699179/23101329/e19c9f6e-f6cb-11e6-83f7-a6da53af6492.png)

**Comment by mp3guy** [comment]
Please see Page 16 Table 2; http://www.thomaswhelan.ie/Whelan16ijrr.pdf

You would need to write new code to manage relocalisation and map merging if you want either of these methods to work on kidnapped sequences.

**Comment by HTLife** [comment]
@mp3guy  Thank you for your quick response.
Before writing new code, I want to test the capability of place recognition module (both DBoW2 and Fern).
After trying out some fern related setting, loop still couldn't been correctly detected (Fern encoding threshold = 0.1).  Would that be the limitation of "fern" method?  Or I didn't tune it right?
