### ISSUE TITLE
After the installation, Kinect V2 can't be found

### ISSUE THREAD

**Issue by Allen-jl** [mp3guy/ElasticFusion#76]
aicrobo@ubuntu:~/ElasticFusion-master/GUI/build$ ./ElasticFusion 
Creating live capture... failed!
DeviceOpen using default: no devices found

So..How can I fix it? THX!

**Comment by zhangduoshou** [comment]
hello,I met the same problem with realsense R200, and haven't solve it until now

**Comment by shanjichao** [comment]
@Allen-jl @zhangduoshou Hello,I met the same problem.Could you help me ,thanks
