### ISSUE TITLE
Run Error:  new Resize()

### ISSUE THREAD

**Issue by jiaxing-li** [mp3guy/ElasticFusion#78]
When I run the ElasticFusion program build with Visual Studio 2013 on Windows 8.1 ,it crashed.

Run into this code when crashing.
GUI\src\MainController.cpp:
   ```
 resizeStream = new Resize(Resolution::getInstance().width(),
                              Resolution::getInstance().height(),
                              Resolution::getInstance().width() / 2,
                              Resolution::getInstance().height() / 2);
```
Crashes when calling the code for the AddPreprocessedShader function of the GlSlProgram class,
```
    if(!prog) {
        prog = glCreateProgram();
    }
```

Why does the glCreateProgram function crash?

@mp3guy

**Comment by jiaxing-li** [comment]
The issues is solved.
Because there are other GLEW libraries in the computer, causing the library to conflict.
I build Pangolin and efusion  into a static library, so use no problem.

**Comment by hughes1217** [comment]
@jiaxing-li I also encountered the same problem, and used your solution to build pangolin and eFusion into a static library, but when building ElasticFusion, there was a link error, unable to resolve the external symbols. Do you know why?

错误	2	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) int __cdecl gettimeofday(struct timeval *,struct timezone *)" (__imp_?gettimeofday@@YAHPEAUtimeval@@PEAUtimezone@@@Z)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	3	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) void * __cdecl mempcpy(void *,void const *,unsigned __int64)" (__imp_?mempcpy@@YAPEAXPEAXPEBX_K@Z)，该符号在函数 "private: char * __cdecl Stopwatch::serialiseTimings(int &)" (?serialiseTimings@Stopwatch@@AEAAPEADAEAH@Z) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	4	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl GPUTexture::GPUTexture(int,int,unsigned int,unsigned int,unsigned int,bool,bool)" (__imp_??0GPUTexture@@QEAA@HHIII_N0@Z)，该符号在函数 "public: __cdecl GUI::GUI(bool,bool)" (??0GUI@@QEAA@_N0@Z) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	5	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: static class Resolution const & __cdecl Resolution::getInstance(int,int)" (__imp_?getInstance@Resolution@@SAAEBV1@HH@Z)，该符号在函数 "public: __cdecl MainController::MainController(int,char * * const)" (??0MainController@@QEAA@HQEAPEAD@Z) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	6	error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: static class Resolution const & __cdecl Resolution::getInstance(int,int)" (__imp_?getInstance@Resolution@@SAAEBV1@HH@Z)	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\LiveLogReader.obj
错误	7	error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: static class Resolution const & __cdecl Resolution::getInstance(int,int)" (__imp_?getInstance@Resolution@@SAAEBV1@HH@Z)	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\RawLogReader.obj
错误	8	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: static class Intrinsics const & __cdecl Intrinsics::getInstance(float,float,float,float)" (__imp_?getInstance@Intrinsics@@SAAEBV1@MMMM@Z)，该符号在函数 "public: __cdecl MainController::MainController(int,char * * const)" (??0MainController@@QEAA@HQEAPEAD@Z) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	9	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: static class Parse const & __cdecl Parse::get(void)" (__imp_?get@Parse@@SAAEBV1@XZ)，该符号在函数 "class std::shared_ptr<class Shader> __cdecl loadProgramFromFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?loadProgramFromFile@@YA?AV?$shared_ptr@VShader@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@00@Z) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	10	error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: static class Parse const & __cdecl Parse::get(void)" (__imp_?get@Parse@@SAAEBV1@XZ)	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\LiveLogReader.obj
错误	11	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: int __cdecl Parse::arg(int,char * *,char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)const " (__imp_?arg@Parse@@QEBAHHPEAPEADPEBDAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)，该符号在函数 "public: __cdecl MainController::MainController(int,char * * const)" (??0MainController@@QEAA@HQEAPEAD@Z) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	12	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: int __cdecl Parse::arg(int,char * *,char const *,float &)const " (__imp_?arg@Parse@@QEBAHHPEAPEADPEBDAEAM@Z)，该符号在函数 "public: __cdecl MainController::MainController(int,char * * const)" (??0MainController@@QEAA@HQEAPEAD@Z) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	13	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: int __cdecl Parse::arg(int,char * *,char const *,int &)const " (__imp_?arg@Parse@@QEBAHHPEAPEADPEBDAEAH@Z)，该符号在函数 "public: __cdecl MainController::MainController(int,char * * const)" (??0MainController@@QEAA@HQEAPEAD@Z) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	14	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl Parse::shaderDir(void)const " (__imp_?shaderDir@Parse@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)，该符号在函数 "class std::shared_ptr<class Shader> __cdecl loadProgramFromFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?loadProgramFromFile@@YA?AV?$shared_ptr@VShader@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@00@Z) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	15	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl FeedbackBuffer::render(struct pangolin::OpenGlMatrix,class Eigen::Matrix<float,4,4,0,4,4> const &,bool,bool)" (__imp_?render@FeedbackBuffer@@QEAAXUOpenGlMatrix@pangolin@@AEBV?$Matrix@M$03$03$0A@$03$03@Eigen@@_N2@Z)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	16	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl Resize::Resize(int,int,int,int)" (__imp_??0Resize@@QEAA@HHHH@Z)，该符号在函数 "public: __cdecl MainController::MainController(int,char * * const)" (??0MainController@@QEAA@HQEAPEAD@Z) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	17	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class std::vector<class GraphNode *,class std::allocator<class GraphNode *> > & __cdecl Deformation::getGraph(void)" (__imp_?getGraph@Deformation@@QEAAAEAV?$vector@PEAVGraphNode@@V?$allocator@PEAVGraphNode@@@std@@@std@@XZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	18	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl IndexMap::renderDepth(float)" (__imp_?renderDepth@IndexMap@@QEAAXM@Z)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	19	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl GlobalModel::renderPointCloud(struct pangolin::OpenGlMatrix,float,bool,bool,bool,bool,bool,bool,int,int)" (__imp_?renderPointCloud@GlobalModel@@QEAAXUOpenGlMatrix@pangolin@@M_N11111HH@Z)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	20	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: struct std::pair<unsigned int,unsigned int> const & __cdecl GlobalModel::model(void)" (__imp_?model@GlobalModel@@QEAAAEBU?$pair@II@std@@XZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	21	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: unsigned int __cdecl GlobalModel::lastCount(void)" (__imp_?lastCount@GlobalModel@@QEAAIXZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	22	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl ElasticFusion::ElasticFusion(int,int,float,float,bool,bool,bool,float,float,float,float,bool,float,bool,bool,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (__imp_??0ElasticFusion@@QEAA@HHMM_N00MMMM0M00V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)，该符号在函数 "public: void __cdecl MainController::launch(void)" (?launch@MainController@@QEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	23	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl ElasticFusion::processFrame(unsigned char const *,unsigned short const *,__int64 const &,class Eigen::Matrix<float,4,4,0,4,4> const *,float,bool)" (__imp_?processFrame@ElasticFusion@@QEAAXPEBEPEBGAEB_JPEBV?$Matrix@M$03$03$0A@$03$03@Eigen@@M_N@Z)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	24	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl ElasticFusion::predict(void)" (__imp_?predict@ElasticFusion@@QEAAXXZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	25	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class IndexMap & __cdecl ElasticFusion::getIndexMap(void)" (__imp_?getIndexMap@ElasticFusion@@QEAAAEAVIndexMap@@XZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	26	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class GlobalModel & __cdecl ElasticFusion::getGlobalModel(void)" (__imp_?getGlobalModel@ElasticFusion@@QEAAAEAVGlobalModel@@XZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	27	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class Ferns & __cdecl ElasticFusion::getFerns(void)" (__imp_?getFerns@ElasticFusion@@QEAAAEAVFerns@@XZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	28	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class Deformation & __cdecl ElasticFusion::getLocalDeformation(void)" (__imp_?getLocalDeformation@ElasticFusion@@QEAAAEAVDeformation@@XZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	29	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class GPUTexture *,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class GPUTexture *> > > & __cdecl ElasticFusion::getTextures(void)" (__imp_?getTextures@ElasticFusion@@QEAAAEAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGPUTexture@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGPUTexture@@@std@@@2@@std@@XZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	30	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class std::vector<class PoseMatch,class std::allocator<class PoseMatch> > const & __cdecl ElasticFusion::getPoseMatches(void)" (__imp_?getPoseMatches@ElasticFusion@@QEAAAEBV?$vector@VPoseMatch@@V?$allocator@VPoseMatch@@@std@@@std@@XZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	31	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class RGBDOdometry const & __cdecl ElasticFusion::getModelToModel(void)" (__imp_?getModelToModel@ElasticFusion@@QEAAAEBVRGBDOdometry@@XZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	32	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: float const & __cdecl ElasticFusion::getConfidenceThreshold(void)" (__imp_?getConfidenceThreshold@ElasticFusion@@QEAAAEBMXZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	33	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl ElasticFusion::setRgbOnly(bool const &)" (__imp_?setRgbOnly@ElasticFusion@@QEAAXAEB_N@Z)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	34	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl ElasticFusion::setIcpWeight(float const &)" (__imp_?setIcpWeight@ElasticFusion@@QEAAXAEBM@Z)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	35	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl ElasticFusion::setPyramid(bool const &)" (__imp_?setPyramid@ElasticFusion@@QEAAXAEB_N@Z)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	36	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl ElasticFusion::setFastOdom(bool const &)" (__imp_?setFastOdom@ElasticFusion@@QEAAXAEB_N@Z)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	37	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl ElasticFusion::setSo3(bool const &)" (__imp_?setSo3@ElasticFusion@@QEAAXAEB_N@Z)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	38	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl ElasticFusion::setFrameToFrameRGB(bool const &)" (__imp_?setFrameToFrameRGB@ElasticFusion@@QEAAXAEB_N@Z)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	39	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl ElasticFusion::setConfidenceThreshold(float const &)" (__imp_?setConfidenceThreshold@ElasticFusion@@QEAAXAEBM@Z)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	40	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl ElasticFusion::setDepthCutoff(float const &)" (__imp_?setDepthCutoff@ElasticFusion@@QEAAXAEBM@Z)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	41	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: bool const & __cdecl ElasticFusion::getLost(void)" (__imp_?getLost@ElasticFusion@@QEAAAEB_NXZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	42	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: int const & __cdecl ElasticFusion::getTick(void)" (__imp_?getTick@ElasticFusion@@QEAAAEBHXZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	43	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: int const & __cdecl ElasticFusion::getTimeDelta(void)" (__imp_?getTimeDelta@ElasticFusion@@QEAAAEBHXZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	44	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl ElasticFusion::setTick(int const &)" (__imp_?setTick@ElasticFusion@@QEAAXAEBH@Z)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	45	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class Eigen::Matrix<float,4,4,0,4,4> const & __cdecl ElasticFusion::getCurrPose(void)" (__imp_?getCurrPose@ElasticFusion@@QEAAAEBV?$Matrix@M$03$03$0A@$03$03@Eigen@@XZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	46	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: int const & __cdecl ElasticFusion::getDeforms(void)" (__imp_?getDeforms@ElasticFusion@@QEAAAEBHXZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	47	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: int const & __cdecl ElasticFusion::getFernDeforms(void)" (__imp_?getFernDeforms@ElasticFusion@@QEAAAEBHXZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	48	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class FeedbackBuffer *,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class FeedbackBuffer *> > > & __cdecl ElasticFusion::getFeedbackBuffers(void)" (__imp_?getFeedbackBuffers@ElasticFusion@@QEAAAEAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVFeedbackBuffer@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVFeedbackBuffer@@@std@@@2@@std@@XZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	49	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl ElasticFusion::computeFeedbackBuffers(void)" (__imp_?computeFeedbackBuffers@ElasticFusion@@QEAAXXZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	50	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl ElasticFusion::savePly(void)" (__imp_?savePly@ElasticFusion@@QEAAXXZ)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	51	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: void __cdecl ElasticFusion::normaliseDepth(float const &,float const &)" (__imp_?normaliseDepth@ElasticFusion@@QEAAXAEBM0@Z)，该符号在函数 "private: void __cdecl MainController::run(void)" (?run@MainController@@AEAAXXZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	52	error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const GPUTexture::RGB" (__imp_?RGB@GPUTexture@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	53	error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const GPUTexture::DEPTH_NORM" (__imp_?DEPTH_NORM@GPUTexture@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	54	error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: static int const Vertex::SIZE" (__imp_?SIZE@Vertex@@2HB)	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	55	error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const FeedbackBuffer::RAW" (__imp_?RAW@FeedbackBuffer@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	56	error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const FeedbackBuffer::FILTERED" (__imp_?FILTERED@FeedbackBuffer@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\MainController.obj
错误	57	error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl Parse::baseDir(void)const " (__imp_?baseDir@Parse@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)，该符号在函数 "public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const __cdecl LiveLogReader::getFile(void)" (?getFile@LiveLogReader@@UEAA?BV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) 中被引用	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\LiveLogReader.obj
错误	58	error LNK1120: 53 个无法解析的外部命令	E:\project\ElasticFusion\ElasticFusion-master\GUI\src\build64\Release\ElasticFusion.exe

**Comment by hughes1217** [comment]
The reason was found. It was not deleted "__declspec(dllimport)". Your solution works, thank you!
