### ISSUE TITLE
Deformed Normal Function

### ISSUE THREAD

**Issue by wine3603** [mp3guy/ElasticFusion#79]
Hi @mp3guy , I have a question about equation 8 in your RSS 2015 paper,  it is about the deformed normal. In which, why did you multi inverse transpose of the transformation matrix ?  
I haven't found this processing in Deformation.cpp. 

If I understand clearly, this transformation is a rotation here,  so R ### -1T should equal to R, 
I checked the original deformation graph paper Sumner 2007, there is a same equation, either without
explain  of this. 
I'm quite weak in math, maybe this is a quite stupid question,  I will be appreciated if you can give more guidance.

**Comment by mp3guy** [comment]
That's how you apply a rotation matrix to a normal vector. It's applied here; https://github.com/mp3guy/ElasticFusion/blob/master/Core/src/Shaders/copy_unstable.vert#L299
