### ISSUE TITLE
Need you advise , what hw devices do ElasticFusion support now , which one is the accurate one?

### ISSUE THREAD

**Issue by xj1982xj** [mp3guy/ElasticFusion#81]

**Comment by xiaozhuka** [comment]
ElasticFusion does support RealSense, but may be not the accurate one

**Comment by xj1982xj** [comment]
Hi xiaozhuka , very thanks. two more question want to consult : 

1. which device do you think is the most accurate one for ElasticFusion , I saw "ElasticFusion Real-time Light Source Detection" video in youtube channel , do you know which hw device this video is using ?    

2. can ElasticFusion has the capability to export the scanned environment as an obj or fbx for other 3d modeling software to use like 3dsmax or maya ?   thanks.

**Comment by DanbingZhu** [comment]
@xiaozhuka Hi, is it possible for you to briefly list the steps required to get elastic fusion working with realsense?

**Comment by ShashankUppoor** [comment]
@xiaozhuka 
Does ElasticFusion with Realsense camera work only on Windows?

**Comment by zhangduoshou** [comment]
@xiaozhuka I have the same question with DanbingZhu

**Comment by whubaichuan** [comment]
> @xiaozhuka I have the same question with DanbingZhu

Hi, do you solve the problem?
