### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_61' when build core

### ISSUE THREAD

**Issue by cians** [mp3guy/ElasticFusion#87]
-- Found SuiteSparse
-- CUDA NVCC target flags: -gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_61,code=sm_61
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cian/ElasticFusion/Core/build
[  9%] [  9%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/Cuda/./cuda_compile_generated_cudafuncs.cu.o
Building NVCC (Device) object CMakeFiles/cuda_compile.dir/Cuda/./cuda_compile_generated_reduce.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_61'
CMake Error at cuda_compile_generated_cudafuncs.cu.o.cmake:206 (message):
  Error generating
  /home/cian/ElasticFusion/Core/build/CMakeFiles/cuda_compile.dir/Cuda/./cuda_compile_generated_cudafuncs.cu.o

make[2]: *** [CMakeFiles/cuda_compile.dir/Cuda/./cuda_compile_generated_cudafuncs.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
nvcc fatal   : Unsupported gpu architecture 'compute_61'
CMake Error at cuda_compile_generated_reduce.cu.o.cmake:206 (message):
  Error generating
  /home/cian/ElasticFusion/Core/build/CMakeFiles/cuda_compile.dir/Cuda/./cuda_compile_generated_reduce.cu.o

make[2]: *** [CMakeFiles/cuda_compile.dir/Cuda/./cuda_compile_generated_reduce.cu.o] Error 1
make[1]: *** [CMakeFiles/efusion.dir/all] Error 2
make: *** [all] Error 2

**Comment by mp3guy** [comment]
Remove 61 from CUDA_ARCH_BIN in CMake
