### ISSUE TITLE
something strange in cuda!

### ISSUE THREAD

**Issue by Xbbei** [mp3guy/ElasticFusion#88]
Hi, man
I build your code, and ./ElasticFusion is work. but shell warning me that "Your GPU "GeForce GTX 850M" isn't int the ICP Step performance database, please add it", "Your GPU "GeForce GTX 850M" isn't int the RGB Step performance database, please add it", "Your GPU "GeForce GTX 850M" isn't int the RGB Res performance database, please add it", "Your GPU "GeForce GTX 850M" isn't int the SO3 Step performance database, please add it". What's problem with my GPU or any other issues?

Thanks very much!

**Comment by mp3guy** [comment]
No problem, you're just getting subpar performance because the tracking block sizes aren't optimal for your particular GPU. You can run GPUTest (passing in a TUM RGB-D Freiburg dataset) to get the strings to add to GPUConfig.h
